config/routes.rb
Rails.application.routes.draw do
  resources :sites
  resources :preferencesites
  resources :translinks
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
root 'static_pages#login'
get  '/home',    to: 'static_pages#home'
get  '/help',    to: 'static_pages#help'
get  '/about',   to: 'static_pages#about'
get  '/contact', to: 'static_pages#contact'
get '/optimize',  to: 'static_pages#optimize'
get '/institute', to: 'static_pages#institute'  
get  '/signup',  to: 'users#new'
post '/signup',  to: 'static_pages#home'
get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
resources :users

post 'translinks/delete_zuordnung', :to => 'translinks#delete_zuordnung'
post 'translinks/read_zuordnung', :to => 'translinks#read_zuordnung'
post 'translinks/optimize', :to => 'translinks#optimize'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.find_by(id: params[:id])
  end

  def help
  end

  def about
  end

  def contact
  end

  def institute
  end

  def optimize
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
Diese Applikation wurde im Rahmen des Kurses "Entwicklung von Anwendungssystemen"
im Master "Operations Research" von Mattis Busse und Niklas Zahn erstellt.
</p>
<br>
<%= link_to 'Zurück zur Startseite', home_path %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Kontakt") %>
<h1>Kontakt</h1>
<p>
Für Fragen zur Applikation wenden Sie sich an das Institut für <a href="https://www.wiwi.uni-hannover.de/produktionswirtschaft.html">Produktionswirtschaft</a>.
</p>
<br>
<%= link_to 'Zurück zur Startseite', home_path %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Hilfe</h1>
<p>
Diese Applikation dient der Eingabe ihrer Präferenzen auf die Anfertigung einer Bachelorarbeit
innerhalb der Institute der wirtschaftswissenschaftlichen Fakultät.
Bitte melden Sie sich an und geben Sie ihre Präferenzwerte in die Eingabemaske ein.
</p>

<% if logged_in? %>
<p>
WICHTIG!
Ein Wert von 1 spiegelt die größtmögliche Präferenz wieder. Ein Wert von 10 die Niedrigste.
Möchten Sie also, beispielhaft, am liebsten ihre Bachelorarbeit am Institut für Produktionswirtschaft schreiben,
geben Sie dort einen Wert von 1 an.
Sie können Werte mehrfach vergeben. Achten Sie auch darauf, dass Sie auch
Werte zwischen 1 und 10 eingeben, wenn dies ihren Präferenzen entspricht, da
das Modell alle Institute mit gleichen Präferenzwerten auch beim Auswahlprozess gleich behandelt.
</p>
<p>
Sie können sich <%= link_to "hier", institute_path %> die Kurzvorstellungen
der einzelnen Institute ansehen.
</p>
<% else %>
Sie können sich <%= link_to "hier", root_path %> anmelden.
<% end %>

app/views/static_pages/home.html.erb
<div class="container" >
  <h1>Willkommen auf der Startseite zur Allokation von Bachelorarbeiten</h1>

<br>
<% if logged_in? && current_user.admin == true %>
  <center>
    <%= link_to "Hier geht es zur Verwaltung der Institute", sites_path, class: "btn btn_home btn-primary", "data-turbolinks": "false"   %><br>
  </center>
      <br>
  <center>
    <%= link_to "Hier geht es zur Optimierung", optimize_path, class: "btn btn_home btn-primary", "data-turbolinks": "false"   %><br>
  </center>
      <br>
<% end %>
<% if logged_in? && current_user.admin == false %>
<h2>
  Wähle über diese Seite deine präferierten Institute!
</h2>
<center>
      <br>
      <center>
      <%= link_to "Hier geht es zur Eingabe der Präferenzen", user_path(current_user), class: "btn btn_home btn-primary", "data-turbolinks": "false"   %><br>
      <center>

        <br>
        <center>
        <%= link_to "Hier geht es zur Vorstellung der Institute", institute_path, class: "btn btn_home btn-primary", "data-turbolinks": "false"   %><br>
        <center>
<br>
<% end %>
<br>

app/views/static_pages/institute.html.erb
<% provide(:title, "Institute") %>
<h1>Institute der wirtschaftswissenschaftlichen Fakultät</h1>


<br><br><br>

<div class="raw">
    <center><div class="image">
      <%= link_to "https://www.wiwi.uni-hannover.de/steuerlehre.html", target: :_blank do %>
      <%= image_tag("Blaufus.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Steuerlehre</b></figcaption>
            <% end %>
          </div></center>

      <center><div class="image">
      <%= link_to "https://www.wiwi.uni-hannover.de/banken_und_finanzierung.html", target: :_blank do %>
      <%= image_tag("Dierkes.jpeg", height: :"100", alt: "Logo") %>
          <figcaption><b>Banken u. Finanzierung</b></figcaption>
          <% end %>
        </div></center>

        <center><div class="image">
            <%= link_to "https://www.wiwi.uni-hannover.de/arbeitsoekonomik.html", target: :_blank do %>
            <%= image_tag("Puhani.jpeg", height: :"100", alt: "Logo") %>
                <figcaption><b>Arbeitsökonomik</b></figcaption>
                <% end %>
              </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/finanzmarkttheorie.html", target: :_blank do %>
          <%= image_tag("Prokopczuk.jpeg", height: :"100", alt: "Logo") %>
          <figcaption><b>Finanzmarkttheorie</b></figcaption>
            <% end %>
          </div></center>
        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/entwicklungs_und_agraroekonomik.html", target: :_blank do %>
            <%= image_tag("Waibel.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Entwicklungs u. Agrarökonomie</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
            <%= link_to "https://www.wiwi.uni-hannover.de/controlling.html", target: :_blank do %>
            <%= image_tag("Schoendube.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Controlling</b></figcaption>
            <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/internationale_finanzwirtschaft.html", target: :_blank do %>
            <%= image_tag("Meyer.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Finanzwirtschaft</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/3834.html?&no_cache=1", target: :_blank do %>
            <%= image_tag("Haunschild.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Arbeitswissenschaft</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/makrooekonomik.html", target: :_blank do %>
            <%= image_tag("Gassebner.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Makroökonomik</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/marketing_und_management.html", target: :_blank do %>
            <%= image_tag("Wiedmann.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Marketing u. Manag.</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/mikrooekonomik.html", target: :_blank do %>
            <%= image_tag("Hoppe.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Mikroökonomik</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/oeffentliche_finanzen.html", target: :_blank do %>
            <%= image_tag("Homburg.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>öfftl. Finanzen</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/personal_und_arbeit.html", target: :_blank do %>
            <%= image_tag("Ridder.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Personal und Arbeit</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/produktionswirtschaft.html", target: :_blank do %>
            <%= image_tag("Helber.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Produktionswirtschaft</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/rechnungslegung.html", target: :_blank do %>
            <%= image_tag("Wielenberg.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Rechnungslegung</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/statistik.html", target: :_blank do %>
            <%= image_tag("Sibbertsen.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Statistik</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/umweltoekonomik.html", target: :_blank do %>
            <%= image_tag("Grote.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Umweltökonomik</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/unternehmensfuehrung.html", target: :_blank do %>
            <%= image_tag("Weber.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Unternehmensführung</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/versicherungsbetriebslehre.html", target: :_blank do %>
            <%= image_tag("vonderSchulenburg.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Versicherungsbetriebslehre</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/wirtschaftsinformatik.html", target: :_blank do %>
            <%= image_tag("Breitner.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Wirtschaftsinformatik</b></figcaption>
          <% end %>
          </div></center>

        <center><div class="image">
          <%= link_to "https://www.wiwi.uni-hannover.de/sozialpolitik.html", target: :_blank do %>
            <%= image_tag("Wagener.jpeg", height: :"100", alt: "Logo") %>
            <figcaption><b>Sozialpolitik</b></figcaption>
          <% end %>
          </div></center>

      </div>

app/views/static_pages/login.html.erb
<%= image_tag("wiwi_neu5a3.jpg", alt: "wiwi_neu5a3 logo") %>
<br>
<br>

<% if logged_in? %>
<% provide(:title, 'Sie sind bereits eingeloggt!') %>
<h1>Sie sind bereits eingeloggt!</h1>
<% else %>

<div class="row">
  <h1>Anmeldung</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.label :matrikelnummer %>
      <%= f.text_field :matrikelnummer, class: 'form-control' %>

      <%= f.label :passwort %>

      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :remember_me, class: "checkbox inline" do %>
      <%= f.check_box :remember_me %>
       <span>Anmeldedaten auf diesem Gerät speichern</span>
      <% end %>
      <br>
      <div class="btn_center">
      <%= f.submit "Anmelden", class: "btn btn_anmelden btn-primary" %></div>
    <% end %>
<br>
    <p class="password"><%= link_to "Passwort vergessen?", new_password_reset_path %></p>

    <br>
    <p class="register"><%= link_to "Noch nicht registriert? Hier geht's zur Registrierung!", signup_path, "data-turbolinks": "false" %></p>
  </div>
</div>
<% end %>

app/views/static_pages/optimize.html.erb
<div class="container">
<% if logged_in? && current_user.admin == true %>

<h1>Optimierung<h1>
  <center>
<%= button_to "Lösche Zuordnung", :controller => 'translinks', :action =>  'delete_zuordnung' %>
</center>

  <center>
<%= button_to "Optimiere", :controller => 'translinks', :action =>  'optimize' %>
</center>

  <center>
<%= button_to "Zuordnung einlesen", :controller => 'translinks', :action =>  'read_zuordnung' %>
</center>
    <br>
<% end %>
</div>
<br>
<%= link_to 'Zurück zur Startseite', home_path %>