config/routes.rb
Rails.application.routes.draw do
  resources :sites
  resources :preferencesites
  resources :translinks
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
root 'static_pages#login'
get  '/home',    to: 'static_pages#home'
get  '/help',    to: 'static_pages#help'
get  '/about',   to: 'static_pages#about'
get  '/contact', to: 'static_pages#contact'
get '/optimize',  to: 'static_pages#optimize'
get '/institute', to: 'static_pages#institute'  
get  '/signup',  to: 'users#new'
post '/signup',  to: 'static_pages#home'
get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
resources :users

post 'translinks/delete_zuordnung', :to => 'translinks#delete_zuordnung'
post 'translinks/read_zuordnung', :to => 'translinks#read_zuordnung'
post 'translinks/optimize', :to => 'translinks#optimize'

end

app/models/preferencesite.rb
class Preferencesite < ApplicationRecord
  validates :preference, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
  has_one :user
end

app/controllers/preferencesites_controller.rb
class PreferencesitesController < ApplicationController
  before_action :set_preferencesite, only: [:show, :edit, :update, :destroy]

  # GET /preferencesites
  # GET /preferencesites.json
  def index
    @preferencesites = Preferencesite.all
  end

  # GET /preferencesites/1
  # GET /preferencesites/1.json
  def show
  end

  # GET /preferencesites/new
  def new
    @preferencesite = Preferencesite.new
    @user = User.find_by(id: params[:id])
  end

  # GET /preferencesites/1/edit
  def edit
  end

  # POST /preferencesites
  # POST /preferencesites.json
  def create
    @preferencesite = Preferencesite.new(preferencesite_params)

    respond_to do |format|
      if @preferencesite.save
        format.html { redirect_to @preferencesite, notice: 'Preferencesite was successfully created.' }
        format.json { render :show, status: :created, location: @preferencesite }
      else
        format.html { render :new }
        format.json { render json: @preferencesite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferencesites/1
  # PATCH/PUT /preferencesites/1.json
  def update
    respond_to do |format|
      if @preferencesite.update(preferencesite_params)
        format.html { redirect_to @preferencesite, notice: 'Preferencesite was successfully updated.' }
        format.json { render :show, status: :ok, location: @preferencesite }
      else
        format.html { render :edit }
        format.json { render json: @preferencesite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferencesites/1
  # DELETE /preferencesites/1.json
  def destroy
    @preferencesite.destroy
    respond_to do |format|
      format.html { redirect_to preferencesites_url, notice: 'Preferencesite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preferencesite
      @preferencesite = Preferencesite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preferencesite_params
      params.require(:preferencesite).permit(:preference, :site_id, :user_id)
    end
end

app/helpers/preferencesites_helper.rb
module PreferencesitesHelper
end

app/views/preferencesites/_form.html.erb
<%= form_with(model: preferencesite, local: true) do |form| %>
  <% if preferencesite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preferencesite.errors.count, "error") %> prohibited this preferencesite from being saved:</h2>

      <ul>
      <% preferencesite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :site_name %>
    <%= form.text_field :site_name, id: :preferencesite_name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :id, id: :user_id %>
  </div>

  <div class="field">
    <%= form.label :preference %>
    <%= form.text_field :preference, id: :preferencesite_preference %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/preferencesites/edit.html.erb
<h1>Editing Preferencesite</h1>

<%= render 'form', preferencesite: @preferencesite %>

<%= link_to 'Show', @preferencesite %> |
<%= link_to 'Back', preferencesites_path %>

app/views/preferencesites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Institute</h1>

<table id="preferencesites" class="display">
  <thead>
    <tr>
      <th>Site</th>
      <th>Preference</th>
    </tr>
  </thead>

  <tbody>
    <% @preferencesites.each do |preferencesite| %>
      <tr>
        <td><%= preferencesite.name %></td>
        <td><%= best_in_place preferencesite.itself, :preference %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', optimize_path %>

app/views/preferencesites/new.html.erb
<h1>New Preferencesite</h1>

<%= render 'form', preferencesite: @preferencesite %>

<%= link_to 'Back', preferencesites_path %>

app/views/preferencesites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Preference:</strong>
  <%= @preferencesite.preference %>
</p>

<p>
  <strong>Site:</strong>
  <%= @preferencesite.site.name %>
</p>

<%= link_to 'Edit', edit_preferencesite_path(@preferencesite), "data-turbolinks": "false" %> |
<%= link_to 'Back', preferencesites_path, "data-turbolinks": "false" %>