config/routes.rb
Rails.application.routes.draw do
  resources :sites
  resources :preferencesites
  resources :translinks
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
root 'static_pages#login'
get  '/home',    to: 'static_pages#home'
get  '/help',    to: 'static_pages#help'
get  '/about',   to: 'static_pages#about'
get  '/contact', to: 'static_pages#contact'
get '/optimize',  to: 'static_pages#optimize'
get '/institute', to: 'static_pages#institute'  
get  '/signup',  to: 'users#new'
post '/signup',  to: 'static_pages#home'
get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
resources :users

post 'translinks/delete_zuordnung', :to => 'translinks#delete_zuordnung'
post 'translinks/read_zuordnung', :to => 'translinks#read_zuordnung'
post 'translinks/optimize', :to => 'translinks#optimize'

end

app/models/site.rb
class Site < ApplicationRecord
  validates :hiwi, numericality: true
  validates :prof, numericality: true
  validates :capincr, numericality: true
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
    @user = User.find_by(id: params[:id])
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :prof, :hiwi)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_with(model: site, local: true) do |form| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :name, id: :site_name %>
  </div>

  <div class="field">
    <%= form.label :Professorenkapazität %>
    <%= form.text_field :prof, id: :site_prof %>
  </div>

  <div class="field">
    <%= form.label :Mitarbeiterkapazität %>
    <%= form.text_field :hiwi, id: :site_hiwi %>
  </div>

  <div class="field">
    <%= form.label :Kapazitätserhöhung %>
    <%= form.text_field :capincr, id: :site_capincr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site, "data-turbolinks": "false" %> |
<%= link_to 'Back', sites_path, "data-turbolinks": "false" %>

app/views/sites/index.html.erb
<% if logged_in? && current_user.admin == true %>
<p id="notice"><%= notice %></p>
<h1>Institute</h1>
<table id="sites" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Professorenkapazität*</th>
      <th>Mitarbeiterkapazität*</th>
      <th>Kapazitätserhöhung(%)</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.name %></td>
        <td><%= best_in_place site.itself, :prof %></td>
        <td><%= best_in_place site.itself, :hiwi %></td>
        <td><%= best_in_place site.itself, :capincr %></td>
        <td><%= link_to 'Löschen', site, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neues Institut anlegen', new_site_path, "data-turbolinks": "false" %> |
<%= link_to 'Zurück zur Startseite', home_path %>

<br><br><br>
<h>*Zum Bearbeiten der Anzahlen von Professoren oder Mitarbeitern in das jeweilige Feld klicken. Bitte geben Sie pro Feld die Anzahl der gesamten Kapazität für diese Mitarbeiterkategorie ein.</h>
<% end %>

app/views/sites/new.html.erb
<h1>Neues Institut anlegen</h1>

<%= render 'form', site: @site %>




<%= link_to 'Zurück', sites_path, "data-turbolinks": "false" %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @site, :name %>
</p>

<p>
  <strong>Prof:</strong>
  <%= best_in_place @site, :prof %>
</p>

<p>
  <strong>Hiwi:</strong>
  <%= best_in_place @site, :hiwi %>
</p>

<p>
  <strong>Capincr:</strong>
  <%= best_in_place @site, :capincr %>
</p>

<%= link_to 'Edit', edit_site_path(@site), "data-turbolinks": "false" %> |
<%= link_to 'Back', sites_path, "data-turbolinks": "false" %>