config/routes.rb
Rails.application.routes.draw do
  resources :sites
  resources :preferencesites
  resources :translinks
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
root 'static_pages#login'
get  '/home',    to: 'static_pages#home'
get  '/help',    to: 'static_pages#help'
get  '/about',   to: 'static_pages#about'
get  '/contact', to: 'static_pages#contact'
get '/optimize',  to: 'static_pages#optimize'
get '/institute', to: 'static_pages#institute'  
get  '/signup',  to: 'users#new'
post '/signup',  to: 'static_pages#home'
get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
resources :users

post 'translinks/delete_zuordnung', :to => 'translinks#delete_zuordnung'
post 'translinks/read_zuordnung', :to => 'translinks#read_zuordnung'
post 'translinks/optimize', :to => 'translinks#optimize'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
  <small>
  von Mattis Busse und Niklas Zahn
  </small>
    <nav>
      <ul>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Kontakt", contact_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
<nav>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? && current_user.admin == false %>
        <li><%= link_to "Home", home_path, "data-turbolinks": "false"%></li>
        <li><%= link_to "Präferenzeingabe", user_path(current_user), "data-turbolinks": "false"%></li>
        <li><%= link_to "Institute", institute_path, "data-turbolinks": "false" %></li> 
        <li><%= link_to "Hilfe",    help_path, "data-turbolinks": "false" %></li>
        <li><%= link_to "Profildaten editieren", edit_user_path(current_user), "data-turbolinks": "false" %></li>
        <li><%= link_to "Ausloggen", logout_path, method: :delete %></li>
        <% end %>
        <% if logged_in? && current_user.admin == true %>
          <li><%= link_to "Home", home_path, "data-turbolinks": "false"%></li>
          <li><%= link_to "Optimierung", optimize_path, "data-turbolinks": "false" %></li>
          <li><%= link_to "Benutzer", users_path, "data-turbolinks": "false"%></li>
          <li><%= link_to "Institute", sites_path, "data-turbolinks": "false"   %></li>
          <li><%= link_to "Profildaten editieren", edit_user_path(current_user), "data-turbolinks": "false" %></li>
          <li>
          <%= link_to "Ausloggen", logout_path, method: :delete %>
          </li>
        <% end %>
        <% if logged_in? == false %>
        <li><%= link_to "Anmelden", root_path, "data-turbolinks": "false"%></li>
        <li><%= link_to "Hilfe",    help_path, "data-turbolinks": "false" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
          <%= render 'layouts/footer' %>
  </body>

</html>